// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ssa_loop
void ssa_loop(NumericVector X, Function pfun, NumericMatrix v, NumericVector params, double tmin, int nsim, int lfun, double tmax, double maxiter, double maxtime, bool printtime, bool optscheck, int kthsave);
RcppExport SEXP ssar_ssa_loop(SEXP XSEXP, SEXP pfunSEXP, SEXP vSEXP, SEXP paramsSEXP, SEXP tminSEXP, SEXP nsimSEXP, SEXP lfunSEXP, SEXP tmaxSEXP, SEXP maxiterSEXP, SEXP maxtimeSEXP, SEXP printtimeSEXP, SEXP optscheckSEXP, SEXP kthsaveSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< Function >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type lfun(lfunSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type maxtime(maxtimeSEXP);
    Rcpp::traits::input_parameter< bool >::type printtime(printtimeSEXP);
    Rcpp::traits::input_parameter< bool >::type optscheck(optscheckSEXP);
    Rcpp::traits::input_parameter< int >::type kthsave(kthsaveSEXP);
    ssa_loop(X, pfun, v, params, tmin, nsim, lfun, tmax, maxiter, maxtime, printtime, optscheck, kthsave);
    return R_NilValue;
END_RCPP
}
