# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ssa_loop <- function(X, pfun, v, params, tmin, nsim, lfun, tmax, maxiter, maxtime, printtime, optscheck, kthsave) {
    invisible(.Call('ssar_ssa_loop', PACKAGE = 'ssar', X, pfun, v, params, tmin, nsim, lfun, tmax, maxiter, maxtime, printtime, optscheck, kthsave))
}

